{% set name = "pylru" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47ad140a63ab9389648dadfbb4330700e0ffeeb28ec04664ee47d37ed133b0f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python >=2.6
    - pip
  run:
    - python >=2.6

test:
  imports:
    - pylru

about:
  home: https://github.com/jlhutch/pylru
  license: LGPL
  license_file: LICENSE.txt
  summary: A least recently used (LRU) cache implementation

extra:
  recipe-maintainers:
    - nehaljwani
